### PR TITLE
export `filterSince` to `vinyl-filter-since`

### PR DESCRIPTION
**Pull request by tunnckoCore**
```
1) source stream should pass through writes:
     Uncaught Error: File not found with singular glob
```
fails before the changes :) look at it.

I tried to resolve it, but I'm no so deep here.

Extract it because it can be useful. Sorry if already have module for that, but I didn't find.

### CODE REVIEW

**Comment by contra** [comment]
Looks fine but https://github.com/tunnckoCore/vinyl-filter-since/blob/master/index.js#L17 doesn't make any sense

**Comment by tunnckoCore** [comment]
It is for debuging and testing, actually higher coverage. Any other/better ideas?
Hmm. Is there some env that travis enables and tell us it running on travis machine? huh, i don't know.

**Comment by contra** [comment]
@tunnckoCore How does that improve test coverage?

**Comment by tunnckoCore** [comment]
@contra I mean test coverage of the `vinyl-filter-since` pkg, not vinyl-fs.

**Comment by tunnckoCore** [comment]
ping @contra

**Comment by contra** [comment]
Still not digging that debug option

**Comment by tunnckoCore** [comment]
@contra okey if I remove it? coverage of `vinyl-filter-since` package will be lower...

**Comment by contra** [comment]
@tunnckoCore I don't understand how it is helping coverage by having that in there

**Comment by tunnckoCore** [comment]
look/run the tests? this one 
```
should not work properly when time is in future
```
this possibility cant be handled/tested if there's no some trick like `debug` "option"

**Comment by tunnckoCore** [comment]
or.... maybe if we add something to the `file` object in this `if` [here](https://github.com/tunnckoCore/vinyl-filter-since/blob/master/index.js#L14-L16)
then check for it.. hm.

**Comment by tunnckoCore** [comment]
no no, cant.

**Comment by tunnckoCore** [comment]
got it? by default it won't go to the next pipe if given date is in future, so this "debug option" help us to determine that scenario and bump coverage.

so the coverage of `vinyl-filter-since` package would be
```
Statements   : 50% ( 17/34 )
Branches     : 25% ( 1/4 )
Functions    : 38.46% ( 5/13 )
Lines        : 50% ( 17/34 )

```

**Comment by doowb** [comment]
@tunnckoCore take a look at this test https://github.com/wearefractal/vinyl-fs/blob/master/test/src.js#L251-L265

The filter since pieces have 100% code coverage here so it shouldn't be hard to do the same in `vinyl-filter-since`

**Comment by tunnckoCore** [comment]
actually it's not correct and [the given date here](https://github.com/wearefractal/vinyl-fs/blob/master/test/src.js#L253) is not in the future.

**Comment by tunnckoCore** [comment]
another way without debug option is to pass ` cb(null, false);` after the if, but it will break next pipe/plugin

but debug option is more elegant and more correct to be done

**Comment by doowb** [comment]
All you have to do is make sure the file didn't go through the pipe. And the current test does that.

**Comment by jonschlinkert** [comment]
just curious. if this is externalized, will there be a reason for other modules to use `vinyl-filter-since`, or will it only be used by vinyl-fs?

**Comment by tunnckoCore** [comment]
> will there be a reason for other modules

maybe, why not?

**Comment by jonschlinkert** [comment]
ah, sorry I see that it's just a plugin. I have no clue what I was looking at earlier

**Comment by tunnckoCore** [comment]
okey, its ready, I'll publish in a bit, and will update this PR.

@jonschlinkert no prob.

**Comment by tunnckoCore** [comment]
done

**Comment by tunnckoCore** [comment]
@contra refactored and no more `debug` option + 100% coverage :)
https://github.com/tunnckoCore/vinyl-filter-since

**Comment by contra** [comment]
Test failng? ^

**Comment by tunnckoCore** [comment]
lol, it fails before that PR, check travis. Even few days before my first pr

**Comment by tunnckoCore** [comment]
cool, thanks :)

**Pull request merged**
